JetBrains/package-search-intellij-plugin

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/PackageSearchToolWindowFactory.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/PackageSearchMetrics.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/PackageSearchPackagePanel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/tree/TreeViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/PackageSearchCentralPanel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/PackageSearchPackageList.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/PackageSearchSearchBar.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/items/PackageGroupHeader.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/side/PackageSearchInfoPanel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/tree/PackageSearchModulesTree.kt

Fixes:
[PKGS-1300](https://youtrack.jetbrains.com/issue/PKGS-1301/Compose-UI-Modules-tree-missing-scrollbars)
[PKGS-1301](https://youtrack.jetbrains.com/issue/PKGS-1299/Compose-UI-Details-pane-is-missing-the-scrollbar)
[PKGS-1284](https://youtrack.jetbrains.com/issue/PKGS-1284/Compose-UI-Details-panel-should-have-a-minimum-width)
add scrollbars on Tree and PackageList, ui improvement to support scrollbars

Adding scrollbars to tree and packages list, added minimum details panel width

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/side/PackageOverviewInfo.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/side/PackageSearchInfoPanel.kt

[PKGS-1298](https://youtrack.jetbrains.com/issue/PKGS-1298/Compose-UI-Details-panel-has-spurious-padding-at-the-top-and-bottom)

Details panel has spurious padding at the top and bottom

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt

[PKGS-1319](https://youtrack.jetbrains.com/agiles/153-2382/current?issue=PKGS-1319)
when module selection changes, the query results were kept showing for a while (until the next search for new modules selection is complete) like the following video shows
Then:
https://github.com/JetBrains/package-search-intellij-plugin/assets/36624359/bf0bcca7-9a47-4bc0-83c4-058af3db573a
Now:
https://github.com/JetBrains/package-search-intellij-plugin/assets/36624359/d10434f4-3cc0-4cee-9f29-9737ff519259

Fix search glitch on module selection change

---

packagesearch.versions.toml
plugin/build.gradle.kts
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/PackageSearchMetrics.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/PackageSearchPackagePanel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/bridge/Components.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/ToolWindowViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/PackageSearchCentralPanel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/side/PackageSearchInfoPanel.kt

Referring to [PKGS-1335](https://youtrack.jetbrains.com/issue/PKGS-1335/Info-panel-default-size-is-too-big)
Rollback to Compose Foundation SplitPane, waiting fix for the jewel's one

Rollback to Compose Foundation SplitPane

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListBuilder.kt

Implement distinctBy in PackageListBuilder build method to prevent id collision
To prevent crashing due to potential double declarations of the same groupId and artifactId, the build method now uses distinctBy to ensure each id is unique.
Refer to [PKGS-1339](https://youtrack.jetbrains.com/issue/PKGS-1349/Project-JUnit-errors-with-multiple-keys-in-SelectableLazyColumn)

PKGS-1339 Fix potential Packages List id collision

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/bridge/Components.kt

see [PKGS-1350](https://youtrack.jetbrains.com/issue/PKGS-1350/UI-Package-action-popup-go-out-of-visible-area)
Change alignment of PopupMenu to end

PKGS-1350 Fix package popup falls out of the visible area

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/bridge/Components.kt

see [PKGS-1350](https://youtrack.jetbrains.com/issue/PKGS-1350/UI-Package-action-popup-go-out-of-visible-area)
Change alignment of PopupMenu to end

232-PKGS-1350 Fix package popup falls out of the visible area

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/bridge/Components.kt

see [PKGS-1350](https://youtrack.jetbrains.com/issue/PKGS-1350/UI-Package-action-popup-go-out-of-visible-area)
Change alignment of PopupMenu to end

233-PKGS-1350 Fix package popup falls out of the visible area

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/bridge/Components.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/side/HeaderAttributesTab.kt

Now badges in the Platform Pane (side panel on the right) will be wrapped instead of resize/clipped

232-Fix badge resize arrangement policy in sidePane - PlatformPane

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/bridge/Components.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/side/HeaderAttributesTab.kt

Now badges in the Platform Pane (side panel on the right) will be wrapped instead of resize/clipped

Fix badges resize-arrangement policy in sidePane - PlatformPane

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/tree/PackageSearchModulesTree.kt

Align the assignment of selected keys in PackageSearchModulesTree as required for the current version of Jewel in EAP

Align API for bundled Jewel Version

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/side/PackageSearchInfoPanel.kt

fixes paddings for tabs in Infobox Tabstrip

233 - Fix InfoPanel Tab paddings

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/side/PackageSearchInfoPanel.kt

fixes paddings for tabs in Infobox Tabstrip

232 - Fix InfoPanel Tab paddings

---

nitrite/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/nitrite/NitriteFilters.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchApplicationCachesService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/ToolWindowViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/tree/TreeViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/tree/PackageSearchModulesTree.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/ApiPackageCacheEntry.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/PackageSearchApiPackageCache.kt
plugin/src/main/resources/messages/packageSearchBundle.properties

The PackageSearchApiPackageCache has been updated to support offline functionality. Refactored the cache system to bypass network calls when operating offline, while optimizing package search parameters.

Update package search cache for offline support

---

plugin/maven/src/main/kotlin/com/jetbrains/packagesearch/plugin/maven/MavenUtils.kt

The importFinished method in MavenImportListener has been modified to receive two additional parameters: importedProjects and newModules. Additionally, unnecessary import lines for javaApi and javaRuntime were removed from MavenUtils.kt. This refinement provides more information during the import finish event for further handling.
(cherry picked from commit d62be21d0e67d86c0369020cc9e225cc4ab50ee5)

Refactor MavenImportListener in MavenUtils

---

nitrite/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/nitrite/NitriteFilters.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchApplicationCachesService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/ToolWindowViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/tree/TreeViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/tree/PackageSearchModulesTree.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/ApiPackageCacheEntry.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/PackageSearchApiPackageCache.kt
plugin/src/main/resources/messages/packageSearchBundle.properties

The PackageSearchApiPackageCache has been updated to support offline functionality. Refactored the cache system to bypass network calls when operating offline, while optimizing package search parameters.

233 - Update package search cache for offline support

---

nitrite/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/nitrite/NitriteFilters.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchApplicationCachesService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/ToolWindowViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/tree/TreeViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/tree/PackageSearchModulesTree.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/ApiPackageCacheEntry.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/PackageSearchApiPackageCache.kt
plugin/src/main/resources/messages/packageSearchBundle.properties

The PackageSearchApiPackageCache has been updated to support offline functionality. Refactored the cache system to bypass network calls when operating offline, while optimizing package search parameters.

232 - Update package search cache for offline support

---

plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/Utils.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListBuilder.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListItem.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListItemEvent.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/Search.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/PackageSearchPackageList.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/PackageSearchApiPackageCache.kt
plugin/src/main/resources/messages/packageSearchBundle.properties

Added new functionality to handle search errors during package search, allowing users to retry the search. Included visual error representation in the UI with a retry link. The search can now also be retried programmatically if it fails.
In this video, the results that shows up are cached.
<video src='https://github.com/JetBrains/package-search-intellij-plugin/assets/10994011/098b4ff1-eceb-4a4b-b51c-d1af97f55422'/>

Implement error handling for search, added log debugging for search caches.

---

plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/Utils.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListBuilder.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListItem.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListItemEvent.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/Search.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/PackageSearchPackageList.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/PackageSearchApiPackageCache.kt
plugin/src/main/resources/messages/packageSearchBundle.properties

Added new functionality to handle search errors during package search, allowing users to retry the search. Included visual error representation in the UI with a retry link. The search can now also be retried programmatically if it fails.
In this video, the results that shows up are cached.
<video src='https://github.com/JetBrains/package-search-intellij-plugin/assets/10994011/098b4ff1-eceb-4a4b-b51c-d1af97f55422'/>

241 - Implement error handling for search, added log debugging for search caches.

---

plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/Utils.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListBuilder.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListItem.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListItemEvent.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/Search.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/PackageSearchPackageList.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/PackageSearchApiPackageCache.kt
plugin/src/main/resources/messages/packageSearchBundle.properties

Added new functionality to handle search errors during package search, allowing users to retry the search. Included visual error representation in the UI with a retry link. The search can now also be retried programmatically if it fails.
In this video, the results that shows up are cached.
<video src='https://github.com/JetBrains/package-search-intellij-plugin/assets/10994011/098b4ff1-eceb-4a4b-b51c-d1af97f55422'/>

233 - Implement error handling for search, added log debugging for search caches. 

---

plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/Utils.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListBuilder.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListItem.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListItemEvent.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/Search.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/PackageSearchPackageList.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/PackageSearchApiPackageCache.kt
plugin/src/main/resources/messages/packageSearchBundle.properties

Added new functionality to handle search errors during package search, allowing users to retry the search. Included visual error representation in the UI with a retry link. The search can now also be retried programmatically if it fails.
In this video, the results that shows up are cached.
<video src='https://github.com/JetBrains/package-search-intellij-plugin/assets/10994011/098b4ff1-eceb-4a4b-b51c-d1af97f55422'/>

232 - Implement error handling for search, added log debugging for search caches. 

---

plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/data/PackageSearchModuleVariant.kt
plugin/gradle/kmp/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/KMPUtils.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/infopanel/asPanelContent.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListItemEvent.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/items/PackageGroupHeader.kt

Fix [PKGS-1371](https://youtrack.jetbrains.com/issue/PKGS-1371/Platform-side-panel-badge-duplicates) - Platform side panel badge duplicate and wrong source-sets

241-Platform side panel badge duplicate and wrong source-sets for KMP headers 

---

plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/data/PackageSearchModuleVariant.kt
plugin/gradle/kmp/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/KMPUtils.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/infopanel/asPanelContent.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListItemEvent.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/items/PackageGroupHeader.kt

This commit improves the handling of attributes within the JetBrains package search plugin. Changes include renaming the `buildAttributesFromRawStrings` function to `parseAttributesFromRawStrings`, and refactoring its implementation for better readability. Additionally, a new `mergeAttributes` function has been added to handle cases where attributes need to be combined, improving code reusability and clarity.
see #55

Platform side panel badge duplicate and wrong source-sets for KMP headers

---

plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/data/PackageSearchModuleVariant.kt
plugin/gradle/kmp/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/KMPUtils.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/infopanel/asPanelContent.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListItemEvent.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/items/PackageGroupHeader.kt

cherry-pick for #55 
This commit improves the handling of attributes within the JetBrains package search plugin. Changes include renaming the `buildAttributesFromRawStrings` function to `parseAttributesFromRawStrings`, and refactoring its implementation for better readability. Additionally, a new `mergeAttributes` function has been added to handle cases where attributes need to be combined, improving code reusability and clarity.

232-Platform side panel badge duplicate and wrong source-sets for KMP headers

---

buildSrc/src/main/kotlin/org/jetbrains/packagesearch/gradle/GeneratePackageSearchObject.kt
plugin/core/build.gradle.kts
plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/services/PackageSearchProjectCachesService.kt
plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/GradleUtils.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchApplicationCachesService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/ApiPackageCacheEntry.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/PackageSearchApiPackageCache.kt

Updated GradleUtils to enhance processing of remote package info. Enhanced logging for better debuggability. Modified handling of packages unknown in backend ensuring that they are properly tracked. Introduced database version control. Changes result in improved reliability and easier issue tracking.

241 - Fix missing packages, enhance logging, cache unknown packages

---

plugin/gradle/build.gradle.kts
plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/Utils.kt

Fix [PKGS-1379](https://youtrack.jetbrains.com/issue/PKGS-1379/Gradle-failure-Cannot-cache-packageSearch.jar-Unsupported-class-file-major-version-61)
remove /tooling from build..\plugin\gradle to avoid wrong class usage in Gradle

Fix PKGS-1379 Remove Gradle tooling classes from main plugin jar

---

plugin/gradle/build.gradle.kts
plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/Utils.kt

Fix [PKGS-1379](https://youtrack.jetbrains.com/issue/PKGS-1379/Gradle-failure-Cannot-cache-packageSearch.jar-Unsupported-class-file-major-version-61)
remove /tooling from build\..\plugin\gradle to avoid wrong class usage in Gradle

241 - Fix PKGS-1379 Remove Gradle tooling classes from main plugin jar

---

plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/Utils.kt

FIx [PKGS-1387](https://youtrack.jetbrains.com/issue/PKGS-1387/Unable-to-Close-Project)
Modified the Project.awaitExternalSystemInitialization() function in Utils.kt to enable cancellation using suspendCancellableCoroutine instead of suspendCoroutine.

232 - Implement cancellation for external system initialization

---

plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/Utils.kt

FIx [PKGS-1387](https://youtrack.jetbrains.com/issue/PKGS-1387/Unable-to-Close-Project)
Modified the Project.awaitExternalSystemInitialization() function in Utils.kt to enable cancellation using suspendCancellableCoroutine instead of suspendCoroutine.

233 - Implement cancellation for external system initialization

---

.github/workflows/publish-release.yml.disabled
buildSrc/build.gradle.kts
plugin/build.gradle.kts

The `build.gradle.kts` file is updated to parse change notes from an environment variable and add it to the plugin XML. This change helps to automate the process of updating change notes. The GitHub workflow file has also been updated to pass the release body as change notes for each build.

Add change notes to plugin XML

---

.github/workflows/publish-release.yml
buildSrc/build.gradle.kts
plugin/build.gradle.kts

The `build.gradle.kts` file is updated to parse change notes from an environment variable and add it to the plugin XML. This change helps to automate the process of updating change notes. The GitHub workflow file has also been updated to pass the release body as change notes for each build.

232 - Add change notes to plugin XML

---

.github/workflows/publish-release.yml
buildSrc/build.gradle.kts
plugin/build.gradle.kts

The `build.gradle.kts` file is updated to parse change notes from an environment variable and add it to the plugin XML. This change helps to automate the process of updating change notes. The GitHub workflow file has also been updated to pass the release body as change notes for each build.

233 - Add change notes to plugin XML

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/ToolWindowViewModel.kt

The handling for showing packages being downloaded in the ToolWindowViewModel has been deactivated. This was done to mitigate PKGS-1389 issue where the UI did not accurately reflect if packages were downloading or not.

241 - Disable packages download UI state in ToolWindowViewModel

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/ToolWindowViewModel.kt

The handling for showing packages being downloaded in the ToolWindowViewModel has been deactivated. This was done to mitigate PKGS-1389 issue where the UI did not accurately reflect if packages were downloading or not.

233 - Disable packages download UI state in ToolWindowViewModel

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/ToolWindowViewModel.kt

The handling for showing packages being downloaded in the ToolWindowViewModel has been deactivated. This was done to mitigate PKGS-1389 issue where the UI did not accurately reflect if packages were downloading or not.

232 - Disable packages download UI state in ToolWindowViewModel

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/ToolWindowViewModel.kt

The handling for showing packages being downloaded in the ToolWindowViewModel has been deactivated. This was done to mitigate PKGS-1389 issue where the UI did not accurately reflect if packages were downloading or not.

Disable packages download UI state in ToolWindowViewModel

---

nitrite/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/nitrite/coroutines/CoroutineObjectRepository.kt
plugin/core/build.gradle.kts
plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/extensions/Contexts.kt
plugin/gradle/base/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/GradleModuleProvider.kt
plugin/gradle/kmp/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/KMPUtils.kt
plugin/gradle/kmp/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/KotlinMultiplatformModuleProvider.kt
plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/GradleDependencyModel.kt
plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/GradleUtils.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/Utils.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/WindowedModuleBuilderContext.kt

This update modifies the caching system and retrieval of modules in Gradle projects. It revamps the caching of declared dependencies by associating them with their SHA hash of the respective build file, and storing them in the local caches.

Fix IDEA-347713 Package Search Plugin high CPU use

---

nitrite/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/nitrite/coroutines/CoroutineObjectRepository.kt
plugin/core/build.gradle.kts
plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/extensions/Contexts.kt
plugin/gradle/base/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/GradleModuleProvider.kt
plugin/gradle/kmp/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/KMPUtils.kt
plugin/gradle/kmp/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/KotlinMultiplatformModuleProvider.kt
plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/GradleDependencyModel.kt
plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/GradleUtils.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/Utils.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/WindowedModuleBuilderContext.kt

This update modifies the caching system and retrieval of modules in Gradle projects. It revamps the caching of declared dependencies by associating them with their SHA hash of the respective build file, and storing them in the local caches.

233 - Fix IDEA-347713 Package Search Plugin high CPU use

---

nitrite/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/nitrite/coroutines/CoroutineObjectRepository.kt
plugin/core/build.gradle.kts
plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/extensions/Contexts.kt
plugin/gradle/base/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/GradleModuleProvider.kt
plugin/gradle/kmp/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/KMPUtils.kt
plugin/gradle/kmp/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/KotlinMultiplatformModuleProvider.kt
plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/GradleDependencyModel.kt
plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/GradleUtils.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/Utils.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/WindowedModuleBuilderContext.kt

This update modifies the caching system and retrieval of modules in Gradle projects. It revamps the caching of declared dependencies by associating them with their SHA hash of the respective build file, and storing them in the local caches.

232 - Fix IDEA-347713 Package Search Plugin high CPU use

---

plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/Utils.kt
plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/GradleModuleTransformer.kt
plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/Utils.kt
plugin/maven/src/main/kotlin/com/jetbrains/packagesearch/plugin/maven/MavenModuleProvider.kt

This commit introduces a critical change in the MavenModuleProvider. The provider now checks if a module is a source set before further processing, thereby improving avoiding duplicates with Gradle synthetic source sets. The isSourceSet check has also been incorporated into the Gradle module for consistency.

Refactor code to add isSourceSet check in MavenModuleProvider

---

plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/Utils.kt
plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/GradleModuleTransformer.kt
plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/Utils.kt
plugin/maven/src/main/kotlin/com/jetbrains/packagesearch/plugin/maven/MavenModuleProvider.kt

This commit introduces a critical change in the MavenModuleProvider. The provider now checks if a module is a source set before further processing, thereby improving avoiding duplicates with Gradle synthetic source sets. The isSourceSet check has also been incorporated into the Gradle module for consistency.

241 - Refactor code to add isSourceSet check in MavenModuleProvider

---

plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/Utils.kt
plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/GradleModuleTransformer.kt
plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/Utils.kt
plugin/maven/src/main/kotlin/com/jetbrains/packagesearch/plugin/maven/MavenModuleProvider.kt

This commit introduces a critical change in the MavenModuleProvider. The provider now checks if a module is a source set before further processing, thereby improving avoiding duplicates with Gradle synthetic source sets. The isSourceSet check has also been incorporated into the Gradle module for consistency.

233 - Refactor code to add isSourceSet check in MavenModuleProvider

---

plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/Utils.kt
plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/GradleModuleTransformer.kt
plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/Utils.kt
plugin/maven/src/main/kotlin/com/jetbrains/packagesearch/plugin/maven/MavenModuleProvider.kt

This commit introduces a critical change in the MavenModuleProvider. The provider now checks if a module is a source set before further processing, thereby improving avoiding duplicates with Gradle synthetic source sets. The isSourceSet check has also been incorporated into the Gradle module for consistency.

232 - Refactor code to add isSourceSet check in MavenModuleProvider

---

plugin/build.gradle.kts

The release channel in the Gradle build file has been updated from "Stable" to "Snapshots". This adjustment helps to accommodate the testing or development process that may require snapshot releases.

Update release channel in Gradle build file.

---

plugin/build.gradle.kts

The release channel in the Gradle build file has been updated from "Stable" to "Snapshots". This adjustment helps to accommodate the testing or development process that may require snapshot releases.

241 - Update release channel in Gradle build file.

---

.github/workflows/publish-release.yml
.github/workflows/publish-snapshot.yml
plugin/build.gradle.kts

This change separates plugin publishing tasks for snapshot and release builds, and pushes them to separate Toolbox Enterprise channels. It also updates the corresponding GitHub workflows accordingly. This provides more flexibility and control over plugin release processes.

233 - Refine plugin publishing tasks in Gradle build.

---

.github/workflows/publish-release.yml
.github/workflows/publish-snapshot.yml
plugin/build.gradle.kts

This change separates plugin publishing tasks for snapshot and release builds, and pushes them to separate Toolbox Enterprise channels. It also updates the corresponding GitHub workflows accordingly. This provides more flexibility and control over plugin release processes.

232 - Refine plugin publishing tasks in Gradle build.

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchApplicationCachesService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/PackageSearchApiPackageCache.kt

Previously the function io.ktor.http.headers was used which is very wrong, since it does not register any header.

Fix http headers for http requests.

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchApplicationCachesService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/PackageSearchApiPackageCache.kt

Previously the function io.ktor.http.headers was used which is very wrong, since it does not register any header.

232 - Fix http headers for http requests.

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchFUSService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/ToolWindowViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/infopanel/InfoPanelViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/tree/TreeViewModel.kt

This commit sets the retry attempts from default (unlimited) to 5 in several classes. The change improves error handling by preventing potential infinite loops in case of persistent failures.

FIX PKGS-1399 Set retry limit in various ViewModel classes

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchFUSService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/ToolWindowViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/infopanel/InfoPanelViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/tree/TreeViewModel.kt

This commit sets the retry attempts from default (unlimited) to 5 in several classes. The change improves error handling by preventing potential infinite loops in case of persistent failures.

241 - FIX PKGS-1399 Set retry limit in various ViewModel classes

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchFUSService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/ToolWindowViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/infopanel/InfoPanelViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/tree/TreeViewModel.kt

This commit sets the retry attempts from default (unlimited) to 5 in several classes. The change improves error handling by preventing potential infinite loops in case of persistent failures.

233 - FIX PKGS-1399 Set retry limit in various ViewModel classes

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchFUSService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/ToolWindowViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/infopanel/InfoPanelViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/tree/TreeViewModel.kt

This commit sets the retry attempts from default (unlimited) to 5 in several classes. The change improves error handling by preventing potential infinite loops in case of persistent failures.

232 - FIX PKGS-1399 Set retry limit in various ViewModel classes

---

plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/services/PackageSearchProjectCachesService.kt
plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/Utils.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/inspections/PackageUpdateInspection.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchSettingsService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/PackageSearchMetrics.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/PackageSearchPackagePanel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/ToolWindowViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/infopanel/InfoPanelViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/tree/TreeViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/Services.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/installActions.kt

Implements [PKGS-1423](https://youtrack.jetbrains.com/issue/PKGS-1423) Create storable settings
This change moves settings to be stored on disk in a new `PackageSearchSettingsService`. This service is responsible for managing options such as filtering for stable packages, installing repositories automatically, and keeping state for UI panel positions. This enables settings to be remembered across IDE restarts. Also, related code has been updated to switch from previous locations to use these persisted settings.

Refactor settings to be persisted on disk

---

plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/services/PackageSearchProjectCachesService.kt
plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/Utils.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/inspections/PackageUpdateInspection.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchSettingsService.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/PackageSearchMetrics.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/PackageSearchPackagePanel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/ToolWindowViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/infopanel/InfoPanelViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/tree/TreeViewModel.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/Services.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/installActions.kt

Implements [PKGS-1423](https://youtrack.jetbrains.com/issue/PKGS-1423) Create storable settings
This change moves settings to be stored on disk in a new `PackageSearchSettingsService`. This service is responsible for managing options such as filtering for stable packages, installing repositories automatically, and keeping state for UI panel positions. This enables settings to be remembered across IDE restarts. Also, related code has been updated to switch from previous locations to use these persisted settings.

241 - Refactor settings to be persisted on disk

---

plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/Utils.kt

It fixes [PKGS-1422 ](https://youtrack.jetbrains.com/issue/PKGS-1422/Hints-for-build-files-can-be-wrong)the calculation of the version text offset by adding a fallback to the parent psiElement's offset if no child elements are present

Fix PKGS-1422 version outdate problem registering for groovy-gradle files

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListBuilder.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListItem.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/PackageSearchPackageList.kt
plugin/src/main/resources/messages/packageSearchBundle.properties

This commit introduces a new view in the package search results for the case when no packages are found. The update includes a 'NoPackagesFoundItem' Composable function, and respective user interface changes. The 'NoPackagesFound' class added to the 'PackageListItem' differentiates between errors and no results in package searches.

241 - Add 'No Packages Found' view to Package List UI

---

plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListBuilder.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListItem.kt
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/PackageSearchPackageList.kt
plugin/src/main/resources/messages/packageSearchBundle.properties

This commit introduces a new view in the package search results for the case when no packages are found. The update includes a 'NoPackagesFoundItem' Composable function, and respective user interface changes. The 'NoPackagesFound' class added to the 'PackageListItem' differentiates between errors and no results in package searches.

Add 'No Packages Found' view to Package List UI

---

.github/workflows/test.yml

The version catalog workflow in the GitHub Actions pipeline has been temporarily disabled. This action was necessary due to pending fixes - the effort to make these fixes has not yet been made. Consequently, until these issues are resolved, the version catalog test workflow will remain inoperative.

233 - Disable version catalog test workflow

---

.run/[KMP] Package Search Plugin.run.xml
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchApplicationCachesService.kt

The commit introduces a new UserAgent to the Ktor client within the PackageSearchApplicationCachesService.kt for the IntelliJApplication. The UserAgent is set using fullApplicationName coming from the service ApplicationInfo. On a different note, an unused environment variable GITHUB_REF has been removed from the Plugin.run.xml configuration file, for cleanup purposes.

241 - Add UserAgent to Ktor client and remove GITHUB_REF from run settings

---

.run/[KMP] Package Search Plugin.run.xml
plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchApplicationCachesService.kt

The commit introduces a new UserAgent to the Ktor client within the PackageSearchApplicationCachesService.kt for the IntelliJApplication. The UserAgent is set using fullApplicationName coming from the service ApplicationInfo. On a different note, an unused environment variable GITHUB_REF has been removed from the Plugin.run.xml configuration file, for cleanup purposes.

233 - Add UserAgent to Ktor client and remove GITHUB_REF from run settings

---

plugin/build.gradle.kts

In the 'plugin/build.gradle.kts' file, the functionality that adds the ']]>' suffix has been temporarily disabled. Further code investigation is needed to determine the impact of this feature.

Temporarily disabled suffix addition in plugin's build file

---

.github/workflows/publish-release.yml
.github/workflows/publish-snapshot.yml.disabled

Removed duplicate steps that publish libraries from GitHub workflows `publish-release.yml` and `publish-snapshot.yml.disabled`. This cleanup ensures that only the necessary steps for publishing to TBE are executed, simplifying the workflows.

Remove redundant Gradle publish steps
