JetBrains/package-search-intellij-plugin

- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/PackageSearchToolWindowFactory.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/bridge/Components.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/bridge/CustomStyles.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/PackageSearchPackageList.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/PackageSearchSearchBar.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/side/PackageOverviewInfo.kt
Migrated Dropdown api to the best one (DropdownLink), that fixes various cosmetics issues like spacing and color with a simple style override
[PKGS-1286](https://youtrack.jetbrains.com/issue/PKGS-1286)
> Migrate Dropdown API to DropdownLink, fixes various cosmetics issues like spacing and color

- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/PackageSearchToolWindowFactory.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/bridge/Components.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/bridge/CustomStyles.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/PackageSearchPackageList.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/PackageSearchSearchBar.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/side/PackageOverviewInfo.kt
Created PackageSearchDropdownLink with a specific Style, injected top level
cherry pick from #4
> Migrate Dropdown API to DropdownLink, fixes various cosmetics issues like spacing and color - IJ233

- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/PackageSearchToolWindowFactory.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/bridge/Components.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/bridge/CustomStyles.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/PackageSearchPackageList.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/PackageSearchSearchBar.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/side/PackageOverviewInfo.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/Utils.kt
Created PackageSearchDropdownLink with a specific Style, injected top level
cherry pick from #4
> Migrate Dropdown API to DropdownLink, fixes various cosmetics issues like spacing and color - IJ232

- buildSrc/src/main/kotlin/org/jetbrains/packagesearch/gradle/ConfigureGradleIntellijPlugin.kt
- plugin/build.gradle.kts
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/PackageSearchPackageList.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/tree/PackageSearchModulesTree.kt
removed shadowing for "jewel" and "compose"
set compose import to compileOnly, because the platform does not contain androidx.ui.tooling package
> removed jewel and compose shadowing

- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/bridge/Components.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/side/HeaderAttributesTab.kt
Now badges in the Platform Pane (side panel on the right) will be wrapped instead of resize/clipped
> 233-Fix badges resize-arrangement policy in sidePane - PlatformPane

- packagesearch.versions.toml
- plugin/build.gradle.kts
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/bridge/CustomStyles.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/side/PackageSearchInfoPanel.kt
This PR fixes Compose and jewel import issues
> Fix missing compose runtime

- packagesearch.versions.toml
- plugin/build.gradle.kts
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/bridge/Components.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/bridge/CustomStyles.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/side/HeaderAttributesTab.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/side/PackageSearchInfoPanel.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/tree/PackageSearchModulesTree.kt
- plugin/src/main/resources/messages/packageSearchBundle.properties
[Update strings and adjust UI layout](https://github.com/JetBrains/package-search-intellij-plugin/commit/88193c0ddab2f601aa809f1e3749161c61798134)
[Fix jewel api usage](https://github.com/JetBrains/package-search-intellij-plugin/commit/ef0dc234f36496f0887ac1fb1949a419ff8291c3)
[Fix missing compose runtime](https://github.com/JetBrains/package-search-intellij-plugin/pull/38)
> 241-Fix compose runtime, cosmetics and api usage

- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/side/PackageSearchInfoPanel.kt
> Fix Jewel API usage

- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/PackageSearchMetrics.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/PackageSearchPackageList.kt
> Fix package item selection background appereance

- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/PackageSearchMetrics.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/PackageSearchPackageList.kt
> 233-Fix package item selection background appereance #41

- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/PackageSearchMetrics.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/PackageSearchPackageList.kt
> 232-Fix package item selection background appereance #41

- plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/data/PackageSearchModuleVariant.kt
- plugin/gradle/kmp/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/KMPUtils.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/infopanel/asPanelContent.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListItemEvent.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/packages/items/PackageGroupHeader.kt
> 232-Platform side panel badge duplicate and wrong source-sets for KMP headers 

- buildSrc/src/main/kotlin/org/jetbrains/packagesearch/gradle/GeneratePackageSearchObject.kt
- plugin/core/build.gradle.kts
- plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/services/PackageSearchProjectCachesService.kt
- plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/GradleUtils.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchApplicationCachesService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/ApiPackageCacheEntry.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/PackageSearchApiPackageCache.kt
Updated GradleUtils to enhance processing of remote package info. Enhanced logging for better debuggability. Modified handling of packages unknown in backend ensuring that they are properly tracked. Introduced database version control. Changes result in improved reliability and easier issue tracking.
> Fix missing packages, enhance logging, cache unknown packages

- buildSrc/src/main/kotlin/org/jetbrains/packagesearch/gradle/GeneratePackageSearchObject.kt
- plugin/core/build.gradle.kts
- plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/services/PackageSearchProjectCachesService.kt
- plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/GradleUtils.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchApplicationCachesService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/ApiPackageCacheEntry.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/PackageSearchApiPackageCache.kt
Updated GradleUtils to enhance processing of remote package info. Enhanced logging for better debuggability. Modified handling of packages unknown in backend ensuring that they are properly tracked. Introduced database version control. Changes result in improved reliability and easier issue tracking.
> 233 - Fix missing packages, enhance logging, cache unknown packages

- buildSrc/src/main/kotlin/org/jetbrains/packagesearch/gradle/GeneratePackageSearchObject.kt
- plugin/core/build.gradle.kts
- plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/services/PackageSearchProjectCachesService.kt
- plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/GradleUtils.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchApplicationCachesService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/ApiPackageCacheEntry.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/PackageSearchApiPackageCache.kt
Refactored the Kotlin Multiplatform Plugin and added plugin parameters in a generated static class. Changes include modifications and relocations of several utilities methods related to KMP attributes and conditions. Environment variables have been introduced to control runtime behavior.
> 232 - Refactor Kotlin Multiplatform Plugin

- plugin/gradle/build.gradle.kts
- plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/Utils.kt
> 233 - Fix PKGS-1379 Remove Gradle tooling classes from main plugin jar

- plugin/gradle/build.gradle.kts
- plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/Utils.kt
> 232 - Fix PKGS-1379 Remove Gradle tooling classes from main plugin jar

- build.gradle.kts
- packagesearch.versions.toml
- plugin/build.gradle.kts
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/bridge/Components.kt
Fixes PKGS-1378 by updating Compose and Jewel (depends on [Jewel #310](https://github.com/JetBrains/jewel/pull/310) merged and released on 0.15.0)
> PKGS-1378 CPU usage spikes for search textField

- build.gradle.kts
- packagesearch.versions.toml
- plugin/build.gradle.kts
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/bridge/Components.kt
Fixes PKGS-1378 by updating Compose and Jewel (depends on [Jewel #310](https://github.com/JetBrains/jewel/pull/310) merged but not released)
> 241 - PKGS-1378 CPU usage spikes for search textField

- plugin/build.gradle.kts
- plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/DirectoryPath.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/fus/PackageSearchEventsLogger.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/fus/PackageSearchFUSEvent.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchFUSService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/tree/TreeViewModel.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/side/PackageOverviewTab.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/Services.kt
The logging system has been refactored to log events using a new PackageSearchFUSEvent sealed interface, to handle logging more uniformly across the code. Furthermore, the sharing behavior of selectedModulesFlow in PackageListViewModel has been adjusted for better performance and readability. These changes help improve the organization and readability of the code while maintaining its functionality.
> Refactor logging system and adjust FUSEvent handling, fix IDEA-347208

- plugin/build.gradle.kts
- plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/DirectoryPath.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/fus/PackageSearchEventsLogger.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/fus/PackageSearchFUSEvent.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchFUSService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/tree/TreeViewModel.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/side/PackageOverviewTab.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/Services.kt
The logging system has been refactored to log events using a new PackageSearchFUSEvent sealed interface, to handle logging more uniformly across the code. Furthermore, the sharing behavior of selectedModulesFlow in PackageListViewModel has been adjusted for better performance and readability. These changes help improve the organization and readability of the code while maintaining its functionality.
> 241 - Refactor logging system and adjust FUSEvent handling, fix IDEA-347208

- plugin/build.gradle.kts
- plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/DirectoryPath.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/fus/PackageSearchEventsLogger.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/fus/PackageSearchFUSEvent.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchFUSService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/tree/TreeViewModel.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/side/PackageOverviewTab.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/Services.kt
The logging system has been refactored to log events using a new PackageSearchFUSEvent sealed interface, to handle logging more uniformly across the code. Furthermore, the sharing behavior of selectedModulesFlow in PackageListViewModel has been adjusted for better performance and readability. These changes help improve the organization and readability of the code while maintaining its functionality.
> 233 - Refactor logging system and adjust FUSEvent handling, fix IDEA-347208

- plugin/build.gradle.kts
- plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/DirectoryPath.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/fus/PackageSearchEventsLogger.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/fus/PackageSearchFUSEvent.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchFUSService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/tree/TreeViewModel.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/panels/side/PackageOverviewTab.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/utils/Services.kt
The logging system has been refactored to log events using a new PackageSearchFUSEvent sealed interface, to handle logging more uniformly across the code. Furthermore, the sharing behavior of selectedModulesFlow in PackageListViewModel has been adjusted for better performance and readability. These changes help improve the organization and readability of the code while maintaining its functionality.
> 232 - Refactor logging system and adjust FUSEvent handling, fix IDEA-347208

- plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/NioPathSerializer.kt
- plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/Utils.kt
- plugin/gradle/base/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/GradleModuleProvider.kt
- plugin/gradle/kmp/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/KMPUtils.kt
- plugin/gradle/kmp/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/KotlinMultiplatformModuleProvider.kt
- plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/GradleUtils.kt
- plugin/maven/src/main/kotlin/com/jetbrains/packagesearch/plugin/maven/MavenModuleProvider.kt
- plugin/maven/src/main/kotlin/com/jetbrains/packagesearch/plugin/maven/MavenUtils.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchFUSService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
This change will avoid unnecessary file readings when they have not been changed, reducing CPU usages on startup.
> Introduced caching for reading Gradle file dependencies.

- plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/NioPathSerializer.kt
- plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/Utils.kt
- plugin/gradle/base/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/GradleModuleProvider.kt
- plugin/gradle/kmp/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/KMPUtils.kt
- plugin/gradle/kmp/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/KotlinMultiplatformModuleProvider.kt
- plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/GradleUtils.kt
- plugin/maven/src/main/kotlin/com/jetbrains/packagesearch/plugin/maven/MavenModuleProvider.kt
- plugin/maven/src/main/kotlin/com/jetbrains/packagesearch/plugin/maven/MavenUtils.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchFUSService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
This change will avoid unnecessary file readings when they have not been changed, reducing CPU usages on startup.
> 241 - Introduced caching for reading Gradle file dependencies.

- plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/NioPathSerializer.kt
- plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/Utils.kt
- plugin/gradle/base/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/GradleModuleProvider.kt
- plugin/gradle/kmp/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/KMPUtils.kt
- plugin/gradle/kmp/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/KotlinMultiplatformModuleProvider.kt
- plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/GradleUtils.kt
- plugin/maven/src/main/kotlin/com/jetbrains/packagesearch/plugin/maven/MavenModuleProvider.kt
- plugin/maven/src/main/kotlin/com/jetbrains/packagesearch/plugin/maven/MavenUtils.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchFUSService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
This change will avoid unnecessary file readings when they have not been changed, reducing CPU usages on startup.
> 233 - Introduced caching for reading Gradle file dependencies.

- plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/NioPathSerializer.kt
- plugin/core/src/main/kotlin/com/jetbrains/packagesearch/plugin/core/utils/Utils.kt
- plugin/gradle/base/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/GradleModuleProvider.kt
- plugin/gradle/kmp/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/KMPUtils.kt
- plugin/gradle/kmp/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/KotlinMultiplatformModuleProvider.kt
- plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/GradleUtils.kt
- plugin/maven/src/main/kotlin/com/jetbrains/packagesearch/plugin/maven/MavenModuleProvider.kt
- plugin/maven/src/main/kotlin/com/jetbrains/packagesearch/plugin/maven/MavenUtils.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchFUSService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/services/PackageSearchProjectService.kt
- plugin/src/main/kotlin/com/jetbrains/packagesearch/plugin/ui/model/packageslist/PackageListViewModel.kt
This change will avoid unnecessary file readings when they have not been changed, reducing CPU usages on startup.
> 232 - Introduced caching for reading Gradle file dependencies.

- plugin/build.gradle.kts
The release channel in the Gradle build file has been updated from "Stable" to "Snapshots". This adjustment helps to accommodate the testing or development process that may require snapshot releases.
> 233 - Update release channel in Gradle build file.

- plugin/maven/src/main/kotlin/com/jetbrains/packagesearch/plugin/maven/MavenUtils.kt
It will be reimplemented with a better solution.
> Maven project hierarchy has been removed due to structural design issues.

- plugin/maven/src/main/kotlin/com/jetbrains/packagesearch/plugin/maven/MavenUtils.kt
It will be reimplemented with a better solution.
> 241 - Maven project hierarchy has been removed due to structural design issues

- plugin/maven/src/main/kotlin/com/jetbrains/packagesearch/plugin/maven/MavenUtils.kt
It will be reimplemented with a better solution.
> 233 - Maven project hierarchy has been removed due to structural design issues.

- plugin/maven/src/main/kotlin/com/jetbrains/packagesearch/plugin/maven/MavenUtils.kt
It will be reimplemented with a better solution.
> 232 - Maven project hierarchy has been removed due to structural design issues.

- plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/Utils.kt
> 241 - Fix PKGS-1422 version outdate problem registering for groovy-gradle files 

- plugin/gradle/src/main/kotlin/com/jetbrains/packagesearch/plugin/gradle/utils/Utils.kt
> 233 - Fix PKGS-1422 version outdate problem registering for groovy-gradle files 
